version: '3'

networks:
  jenkins:
    external: false

services:
  jenkins:
    user: root
    container_name: 'jenkins'
    image: jenkins/jenkins:lts
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - jenkins
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - "8080:8080"
      - "50000:50000"
    command: >
      bash -c "
      curl -fsSL https://get.docker.com -o get-docker.sh &&
      sh get-docker.sh &&
      exec /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
