pipeline {
  agent any

  options {
    timestamps()
    timeout(time: 1, unit: 'MINUTES')
  }

  environment {
    DIR_REPO='repo'
    LOCAL_PATH=pwd()
  }

  parameters {
    choice(name:'ENVIRONMENT', choices:['DEV','HOMOLOG','PRODUCTION'], description:'Defina um ambiente para executar o pipeline')
    string(name: 'ARQUIVO', defaultValue: 'arquivo.txt', description: 'Nome do arquivo a se criar.')
    text(name: 'CONTEUDO', defaultValue: '', description: 'Entre com um conteúdo para o arquivo')
    booleanParam(name: 'CRIAR', defaultValue: true, description: 'Criar ou não o arquivo ?')
  }

  stages {
    stage('Variaveis de Ambiente'){
      steps {
        echo "DIR_REPO = ${DIR_REPO}"
        echo "LOCAL_PATH = ${LOCAL_PATH}"
      }
    }

    stage('Parametros do Ambiente'){
      when{
        anyOf{
          environment name: 'CRIAR', value: 'true'
          environment name: 'ENVIRONMENT', value: 'PRODUCTION'
        }
      }
      steps{
        echo "Arquivo a se criar: ${params.ARQUIVO}"
        echo "Conteúdo do arquivo: ${params.CONTEUDO}"
        sh "echo ${params.CONTEUDO} > ${params.ARQUIVO}"
      }
    }
  }

  post {
    always {
      echo "Pipeline finalizado."
    }
  
    success {
      echo "Pipeline finalizado com Sucesso"
    }
  
    failure {
      echo "Pipeline finalizado com Falha"
    }
  }
}